# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default
  
variables:
  buildConfiguration: 'Release'

# Steps to run in the pipeline
steps:
  - task: DotNetCoreCLI@2 
    displayName: 'Build CommonLib'
    inputs:
      command: 'build' 
      arguments: '--configuration $(buildConfiguration)' 
      projects: 'dotnew-SonarQube.csproj' 

  - task: DotNetCoreCLI@2 
    displayName: 'Pack CommonLib'
    inputs:
      command: 'pack' 
      arguments: '--configuration $(buildConfiguration)' 
      packagesToPack: 'dotnew-SonarQube.csproj' 
      nobuild: true 
      versioningScheme: 'off' 

  - task: DotNetCoreCLI@2
    displayName: 'Push NuGet package to hello-world-feed'
    inputs:
      targetType: 'inline'
      script: |
        # Define the path to the NuGet package
        $packagePath = "$(System.DefaultWorkingDirectory)/bin/Release/dotnew-SonarQube.1.0.0.nupkg"
        
        # Define the NuGet feed source and API key
        $nugetSource = "hello-world-feed"
        $apiKey = "az"  # Replace "az" with your actual API key
        
        # Push the NuGet package to the feed
        dotnet nuget push --source $nugetSource --api-key $apiKey $packagePath
