trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default
  
variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet package with version'
    inputs:
      command: 'pack'
      arguments: '-p:Version=1.0.$(Build.BuildId)'
      packagesToPack: 'dotnew-SonarQube.csproj'
      nobuild: true

  - task: DotNetCoreCLI@2
    displayName: 'Push NuGet package to hello-world-feed'
    inputs:
      targetType: 'inline'
      script: |
        # Define the path to the NuGet package
        $packagePath = "$(System.DefaultWorkingDirectory)/**/*.nupkg"
        
        # Define the NuGet feed source and API key
        $nugetSource = "hello-world-feed"
        $apiKey = "az"  # Replace "az" with your actual API key
        
        # Push the NuGet package to the feed
        dotnet nuget push --source $nugetSource --api-key $apiKey $packagePath
