# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: default
  
variables:
  buildConfiguration: 'Release'

# Steps to run in the pipeline
steps:
  - task: DotNetCoreCLI@2 
    displayName: 'Build CommonLib'
    inputs:
      command: 'build' 
      arguments: '--configuration $(buildConfiguration)' 
      projects: 'dotnew-SonarQube.csproj' 

  - task: DotNetCoreCLI@2 
    displayName: 'Pack CommonLib'
    inputs:
      command: 'pack' 
      arguments: '--configuration $(buildConfiguration)' 
      packagesToPack: 'dotnew-SonarQube.csproj' 
      nobuild: true 
      versioningScheme: 'off' 

  - task: NuGetCommand@2 
    displayName: 'Push CommonLib to hello-world-feed'
    inputs:
      command: 'push' 
      feedsToUse: 'select' 
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg' 
      nuGetFeedType: 'internal' 
      publishVstsFeed: 'hello-world-feed' 
      versioningScheme: 'off' 
      allowPackageConflicts: true 
